import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";
import { Cart } from "@/components/Cart";
import { PageBody } from "@/components/PageBody";
import { UserProvider } from "@/contexts/UserContext";
import { Header } from "@/components/Header";
import { SearchProvider } from "@/contexts/SearchContext";
import { ModalProvider } from "@/contexts/ModalContext";
import { CartContext, CartProvider } from "@/contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex overflow-y-hidden`}
      >
        <UserProvider>
          <SearchProvider>
            <ModalProvider>
              <CartProvider>
                <Menu />
                <PageBody>{children}</PageBody>
                <Cart />
              </CartProvider>
            </ModalProvider>
          </SearchProvider>
        </UserProvider>
      </body>
    </html>
  );
}
